export const APP_MONTH = 9

export const ACCOUNTS_GLOB = {
        "admin_0": {id: "0", email: "admin@email.com", password: "$2b$10$5DYvM/QCeCYOtJqz7U95PueI2mFgP9Tt6cuLdHgxwLy5ojd0IMHbC", role: "Admin", token: "1"},
        "user_1": {id: "user_1", email: "user@email.com", password: "$2b$10$3FHn8ZqxmLnrIkUbjildO.gQ5fxD62GOotAse2xIHYgTcamHGzkF2", role: "User", token: "2"},
    }

export const APARTMENTS_GLOB = {
  "1": {
    id: "1",
    title: "Apt. 101",
    description: "Some information about the apartment",
    features: ["3 roommates", "In-unit washer/dryer", "Dope apartment", "That's all"],
    price: 440,
    maintenanceRequested: false,
    technicianSent: false,
  },
  "2": {
    id: "2",
    title: "Apt. 102",
    description: "Stuff about THIS apartment",
    features: ["2 roommates", "Free donkey", "Also dope"],
    price: 500,
    maintenanceRequested: false,
    technicianSent: false,
  },
  "3": {
    id: "3",
    title: "Apt. 103",
    description: "Currently filled apartment",
    features: ["Beautiful wallpaper", "Office space", "Comes with a shark tank"],
    price: 445,
    maintenanceRequested: false,
    technicianSent: false,
  },
  "4": {
    id: "4",
    title: "Apt. 104",
    description: "Ground floor unit with high drama",
    features: ["1 mystery noise at night", "Includes tool set", "Extra large closet", "Built-in suspense"],
    price: 440,
    maintenanceRequested: true,
    technicianSent: false,
  },
  "5": {
    id: "5",
    title: "Apt. 201",
    description: "Mid-level pad with views",
    features: ["1 quietly judgey roommate", "Sunlit balcony", "Slightly squishy hardwood", "Pre-stocked spice rack"],
    price: 460,
    maintenanceRequested: false,
    technicianSent: false,
  },
  "6": {
    id: "6",
    title: "Apt. 202",
    description: "The gamer sanctuary",
    features: ["Gigabit fiber pre-routed", "Soundproof-ish walls", "RGB ambient lighting", "Mini fridge in hall"],
    price: 460,
    maintenanceRequested: false,
    technicianSent: false,
  },
  "7": {
    id: "7",
    title: "Apt. 203",
    description: "Cool apartment here!",
    features: ["2 roommates", "Widescreen TV", "Lots of storage"],
    price: 480,
    maintenanceRequested: false,
    technicianSent: false,
  },
  "8": {
    id: "8",
    title: "Apt. 204",
    description: "Corner unit with main character energy",
    features: ["Wrap-around windows", "Espresso machine", "Heated bathroom floor"],
    price: 485,
    maintenanceRequested: false,
    technicianSent: false,
  },
  "9": {
    id: "9",
    title: "Apt. 301",
    description: "Top floor penthouse",
    features: ["High ceilings", "Skylight above bed", "No overhead footsteps"],
    price: 515,
    maintenanceRequested: false,
    technicianSent: false,
  },
  "10": {
    id: "10",
    title: "Apt. 302",
    description: "A chef's dream with zero space for guests",
    features: ["Gas range stove", "Granite counter top", "Emotional support air fryer", "Very cozy kitchen"],
    price: 500,
    maintenanceRequested: false,
    technicianSent: false,
  },
  "11": {
    id: "11",
    title: "Apt. 303",
    description: "The luxury suite",
    features: ["Private rooftop access", "Chandelier in bathroom", "Built-in pizza oven", "Fancy golden sink"],
    price: 525,
    maintenanceRequested: false,
    technicianSent: false,
  },
  "12": {
    id: "12",
    title: "Apt. 304",
    description: "Tranquilo Lugar",
    features: ["Deep soaking tub", "Unmatched sunset view", "Surprisingly great acoustic insulation"],
    price: 520,
    maintenanceRequested: false,
    technicianSent: false,
  },
};

export const PAYMENTS_GLOB = {
    "pay_1234": {
        id: "pay_1234",
        linkedApartmentId: "3",
        month: 6,
        amount: 445,
        paidInFull: true,
    },
    "pay_5678": {
        id: "pay_5678",
        linkedApartmentId: "3",
        month: 7,
        amount: 445,
        paidInFull: true,
    },

    // Apt. 104 (Price: 440, History: Months 5, 6, 7, 8)
    "pay_0001": {
        id: "pay_0001",
        linkedApartmentId: "4",
        month: 5,
        amount: 440,
        paidInFull: true,
    },
    "pay_0002": {
        id: "pay_0002",
        linkedApartmentId: "4",
        month: 6,
        amount: 440,
        paidInFull: true,
    },
    "pay_0003": {
        id: "pay_0003",
        linkedApartmentId: "4",
        month: 7,
        amount: 440,
        paidInFull: true,
    },

    // Apt. 201 (Price: 460, History: Months 6, 7, 8)
    "pay_0004": {
        id: "pay_0004",
        linkedApartmentId: "5",
        month: 6,
        amount: 460,
        paidInFull: true,
    },
    "pay_0005": {
        id: "pay_0005",
        linkedApartmentId: "5",
        month: 7,
        amount: 460,
        paidInFull: true,
    },

    // Apt. 202 (Price: 460, History: Months 4, 5, 6, 7, 8)
    "pay_0006": {
        id: "pay_0006",
        linkedApartmentId: "6",
        month: 4,
        amount: 460,
        paidInFull: true,
    },
    "pay_0007": {
        id: "pay_0007",
        linkedApartmentId: "6",
        month: 5,
        amount: 460,
        paidInFull: true,
    },
    "pay_0008": {
        id: "pay_0008",
        linkedApartmentId: "6",
        month: 6,
        amount: 460,
        paidInFull: true,
    },
    "pay_0009": {
        id: "pay_0009",
        linkedApartmentId: "6",
        month: 7,
        amount: 460,
        paidInFull: true,
    },

    // Apt. 204 (Price: 485, History: Months 3, 4, 5, 6, 7, 8)
    "pay_0010": {
        id: "pay_0010",
        linkedApartmentId: "8",
        month: 3,
        amount: 485,
        paidInFull: true,
    },
    "pay_0011": {
        id: "pay_0011",
        linkedApartmentId: "8",
        month: 4,
        amount: 485,
        paidInFull: true,
    },
    "pay_0012": {
        id: "pay_0012",
        linkedApartmentId: "8",
        month: 5,
        amount: 485,
        paidInFull: true,
    },
    "pay_0013": {
        id: "pay_0013",
        linkedApartmentId: "8",
        month: 6,
        amount: 485,
        paidInFull: true,
    },
    "pay_0014": {
        id: "pay_0014",
        linkedApartmentId: "8",
        month: 7,
        amount: 485,
        paidInFull: true,
    },

    // Apt. 301 (Price: 515, History: Months 5, 6, 7, 8)
    "pay_0015": {
        id: "pay_0015",
        linkedApartmentId: "9",
        month: 5,
        amount: 515,
        paidInFull: true,
    },
    "pay_0016": {
        id: "pay_0016",
        linkedApartmentId: "9",
        month: 6,
        amount: 515,
        paidInFull: true,
    },
    "pay_0017": {
        id: "pay_0017",
        linkedApartmentId: "9",
        month: 7,
        amount: 515,
        paidInFull: true,
    },

    // Apt. 302 (Price: 500, History: Months 6, 7, 8)
    "pay_0018": {
        id: "pay_0018",
        linkedApartmentId: "10",
        month: 6,
        amount: 500,
        paidInFull: true,
    },
    "pay_0019": {
        id: "pay_0019",
        linkedApartmentId: "10",
        month: 7,
        amount: 500,
        paidInFull: true,
    },

    // Apt. 303 (Price: 525, History: Months 4, 5, 6, 7, 8)
    "pay_0020": {
        id: "pay_0020",
        linkedApartmentId: "11",
        month: 4,
        amount: 525,
        paidInFull: true,
    },
    "pay_0021": {
        id: "pay_0021",
        linkedApartmentId: "11",
        month: 5,
        amount: 525,
        paidInFull: true,
    },
    "pay_0022": {
        id: "pay_0022",
        linkedApartmentId: "11",
        month: 6,
        amount: 525,
        paidInFull: true,
    },
    "pay_0023": {
        id: "pay_0023",
        linkedApartmentId: "11",
        month: 7,
        amount: 525,
        paidInFull: true,
    },

    // Apt. 304 (Price: 520, History: Months 5, 6, 7, 8)
    "pay_0024": {
        id: "pay_0024",
        linkedApartmentId: "12",
        month: 5,
        amount: 520,
        paidInFull: true,
    },
    "pay_0025": {
        id: "pay_0025",
        linkedApartmentId: "12",
        month: 6,
        amount: 520,
        paidInFull: true,
    },
    "pay_0026": {
        id: "pay_0026",
        linkedApartmentId: "12",
        month: 7,
        amount: 520,
        paidInFull: true,
    },

    // --- Month 8 Payments ---
    "pay_0027": {
        id: "pay_0027",
        linkedApartmentId: "1",
        month: 8,
        amount: 440,
        paidInFull: false,
    },
    "pay_0028": {
        id: "pay_0028",
        linkedApartmentId: "2",
        month: 8,
        amount: 500,
        paidInFull: false,
    },
    "pay_0029": {
        id: "pay_0029",
        linkedApartmentId: "3",
        month: 8,
        amount: 445,
        paidInFull: false,
    },
    "pay_0030": {
        id: "pay_0030",
        linkedApartmentId: "4",
        month: 8,
        amount: 440,
        paidInFull: false,
    },
    "pay_0031": {
        id: "pay_0031",
        linkedApartmentId: "5",
        month: 8,
        amount: 460,
        paidInFull: true,
    },
    "pay_0032": {
        id: "pay_0032",
        linkedApartmentId: "6",
        month: 8,
        amount: 460,
        paidInFull: false,
    },
    "pay_0033": {
        id: "pay_0033",
        linkedApartmentId: "7",
        month: 8,
        amount: 480,
        paidInFull: false,
    },
    "pay_0034": {
        id: "pay_0034",
        linkedApartmentId: "8",
        month: 8,
        amount: 485,
        paidInFull: false,
    },
    "pay_0035": {
        id: "pay_0035",
        linkedApartmentId: "9",
        month: 8,
        amount: 515,
        paidInFull: true,
    },
    "pay_0036": {
        id: "pay_0036",
        linkedApartmentId: "10",
        month: 8,
        amount: 500,
        paidInFull: false,
    },
    "pay_0037": {
        id: "pay_0037",
        linkedApartmentId: "11",
        month: 8,
        amount: 525,
        paidInFull: true,
    },
    "pay_0038": {
        id: "pay_0038",
        linkedApartmentId: "12",
        month: 8,
        amount: 520,
        paidInFull: false,
    }
}